module-name: btp-operator
rc-tag: 060923
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/btp-manager:060923
whitesource:
  language: golang-mod
  subprojects: false
  exclude:
    - "**/*_test.go"
