module-name: btp-operator
rc-tag: 452543
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/btp-manager:452543
whitesource:
  language: golang-mod
  subprojects: false
  exclude:
    - "**/*_test.go"
