module-name: btp-operator
rc-tag: lj-d3bug
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/btp-manager:lj-d3bug
whitesource:
  language: golang-mod
  subprojects: false
  exclude:
    - "**/*_test.go"
