module-name: btp-operator
rc-tag: hhfhfgfghf
protecode:
  - europe-docker.pkg.dev/kyma-project/prod/btp-manager:hhfhfgfghf
whitesource:
  language: golang-mod
  subprojects: false
  exclude:
    - "**/*_test.go"
