---
# Source: sap-btp-operator/templates/deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/instance: sap-btp-operator
    app.kubernetes.io/name: sap-btp-operator
  name: sap-btp-operator-controller-manager
  namespace: kyma-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
      app.kubernetes.io/instance: sap-btp-operator
      app.kubernetes.io/name: sap-btp-operator
  template:
    metadata:
      annotations:
        checksum/config: 5d31d3aa833825d02f494b5a24cb0f2d6c26ae0ecaf0293a571de6d149f666a9
        checksum/config-webhook: 24fd6c741b9caffd455cd6c71285d78293f24ef7602b6851ef8c090112df555f
        sidecar.istio.io/inject: "false"
      labels:
        control-plane: controller-manager
        app.kubernetes.io/instance: sap-btp-operator
        app.kubernetes.io/name: sap-btp-operator
    spec:
      containers:
        - args:
            - --secure-listen-address=0.0.0.0:8443
            - --upstream=http://127.0.0.1:8080/
            - --logtostderr=true
            - --v=10
          image: quay.io/brancz/kube-rbac-proxy:v0.11.0
          name: kube-rbac-proxy
          ports:
            - containerPort: 8443
              name: https
        - args:
            - --metrics-addr=127.0.0.1:8080
          command:
            - /manager
          envFrom:
            - configMapRef:
                name: sap-btp-operator-config
          image: ghcr.io/sap/sap-btp-service-operator/controller:v0.2.5
          imagePullPolicy: IfNotPresent
          name: manager
          ports:
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 250m
              memory: 200Mi
            requests:
              cpu: 10m
              memory: 20Mi
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cert
              readOnly: true
      terminationGracePeriodSeconds: 10
      priorityClassName: kyma-system
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: webhook-server-cert
