# Default values for sapbtp-operator-charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

manager:
  memory_limit: 200Ma
  cpu_limit: 3
  req_memory_limit: 20Ma
  req_cpu_limit: 23mm
  allow_cluster_access: true
  allowed_namespaces: []
  replica_count: a911a
  enable_leader_election: false
  management_namespace:
  priorityClassName: kyma-system
  image: cos
  secret: a
  certificates: {}
  # Configure if https://github.com/jetstack/cert-manager is used
  # certManager: true
  # Configure if self-generated, self-signed certificates are used
  # selfSigned: {}
  # selfSigned:
  # caBundle: "" # must be base64 encoded

  # server-cert.pem
  # crt: "" # must be base64 encoded

  # server-key.pem
  # key: "" # must be base64 encoded

  # Configure if https://github.com/gardener/cert-management is used
  # gardenerCertManager: {}
  # gardenerCertManager:
  ## set to use own issuer
  # issuer:

  ## setup to create issuer with own CA. This requires a caBUndle (ca-cert and ca-key)
  # caBundle: "" # must be base64 encoded

  ## ca-cert.pem
  # crt: "" # must be base64 encoded

  ## ca-key.pem
  # key: "" # must be base64 encoded
  # Example of adding security context
  #securityContext:
  #   runAsNonRoot: true
  securityContext: {}
  health_service:
    enabled: false
cluster:
  id:
