---
# Source: sap-btp-operator/templates/configmap.yml
apiVersion: v1
data:
  CLUSTER_ID: e13e849b-cab8-409a-abaf-652d1af01afa
  MANAGEMENT_NAMESPACE: default
  RELEASE_NAMESPACE: default
  ALLOW_CLUSTER_ACCESS: "true"
kind: ConfigMap
metadata:
  name: sap-btp-operator-config
  namespace: default
