---
# Source: sap-btp-operator/templates/configmap.yml
apiVersion: v1
data:
  CLUSTER_ID: e0346294-5214-4075-b35b-260f34713f8a
  MANAGEMENT_NAMESPACE: default
  RELEASE_NAMESPACE: default
  ALLOW_CLUSTER_ACCESS: "true"
kind: ConfigMap
metadata:
  name: sap-btp-operator-config
  namespace: default
