---
# Source: sap-btp-operator/templates/configmap.yml
apiVersion: v1
data:
  CLUSTER_ID: a463c4d8-fcad-4acc-8f1c-ce6b105179ed
  MANAGEMENT_NAMESPACE: default
  RELEASE_NAMESPACE: default
  ALLOW_CLUSTER_ACCESS: "true"
kind: ConfigMap
metadata:
  name: sap-btp-operator-config
  namespace: default
