---
# Source: sap-btp-operator/templates/configmap.yml
apiVersion: v1
data:
  CLUSTER_ID: 7dbad4a5-9cb4-4b5f-a974-3b248b397933
  MANAGEMENT_NAMESPACE: default
  RELEASE_NAMESPACE: default
  ALLOW_CLUSTER_ACCESS: "true"
kind: ConfigMap
metadata:
  name: sap-btp-operator-config
  namespace: default
