---
# Source: sap-btp-operator/templates/configmap.yml
apiVersion: v1
data:
  CLUSTER_ID: 6a668a27-b93a-468d-90dc-0fe7faf001d1
  MANAGEMENT_NAMESPACE: default
  RELEASE_NAMESPACE: default
  ALLOW_CLUSTER_ACCESS: "true"
kind: ConfigMap
metadata:
  name: sap-btp-operator-config
  namespace: default
