name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Download Chart
      run: |
        curl -L https://github.com/SAP/sap-btp-service-operator/releases/download/v0.3.3/sap-btp-operator-v0.3.3.tgz > charts.tgz
        mkdir module-chart
        tar zxvf charts.tgz -C module-chart
    - name: Print
      working-directory: module-chart
      run: |
        ls -l
    - name: Install Helm
      run: | 
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh
    - name: Print Helm v
      run: helm version
    - name: Render templates
      working-directory: module-chart
      run: helm template ljtest 