name: Manual workflow

env:
  ORG: ukff
  BTP_MANAGER_REPO: btp-manager
  GIT_EMAIL: <>
  GIT_NAME: BTP Manager

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        default: 'World'
        required: true

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Download Chart
      run: |
        curl -L https://github.com/SAP/sap-btp-service-operator/releases/download/v0.3.3/sap-btp-operator-v0.3.3.tgz > charts.tgz
        tar zxvf charts.tgz 
    - name: Print
      working-directory: sap-btp-operator
      run: |
        ls -l
    - name: Install Helm
      run: | 
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh
    - name: Print Helm v
      run: helm version
    - name: Render templates
      working-directory: sap-btp-operator
      run: |
        helm template v3 . --output-dir rendered
    - name: Print 
      working-directory: sap-btp-operator/rendered/sap-btp-operator/templates
      run: ls
    
    - name: Setup GitHub config
      run: |
        git config --global user.email $GIT_EMAIL
        git config --global user.name $GIT_NAME
    - name: Clone Kyma Repo 
      run: |
        git clone https://github.com/$ORG/$KYMA_REPO.git
    - name: Create Branch
      working-directory: kyma
      run: |
        git checkout -B $BRANCH_NAME
    - name: Add module template
      working-directory: sap-btp-operator
      run: yes | cp -rf . $BTP_MANAGER_REPO
    - name: Commit Changes
      working-directory: kyma
      run: |
        git add .
        git commit -m "Update $TEMPLATE_NAME"
    - name: Push Changes
      working-directory: kyma
      run: |
        git remote set-url origin https://${{ secrets.ACCESS_TOKEN }}@github.com/$ORG/$BTP_MANAGER_REPO.git
        git push --set-upstream origin $BRANCH_NAME -f
    - name: Create PR if needed
      working-directory: kyma
      shell: bash
      run: |
        prs=$(gh pr list -R https://github.com/$ORG/$BTP_MANAGER_REPO/ -A ukff --state open --json headRefName | jq -r '.[] | .headRefName')
       
        if  echo $prs | tr " " '\n' | grep -F -q -x $BRANCH_NAME; then
            echo "open pr already exists, no need to create new one, pr will be updated by push from previous step"
            exit 0
        fi
       
        gh pr create -B main -R https://github.com/$ORG/$BTP_MANAGER_REPO/ --title "Promote BTP Manager to ( $TAG )" --fill
      env:
        GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}